const createKatakanaStore = () => {
    const store = new Map();
    const data = [
        {english: 'a', jap: 'ア'},
        {english: 'i', jap: 'イ'},
        {english: 'u', jap: 'ウ'},
        {english: 'e', jap: 'エ'},
        {english: 'o', jap: 'オ'},
        {english: 'ka', jap: 'カ'},
        {english: 'ki', jap: 'キ'},
        {english: 'ku', jap: 'ク'},
        {english: 'ke', jap: 'ケ'},
        {english: 'ko', jap: 'コ'},
        {english: 'kya', jap: 'キャ'},
        {english: 'kyu', jap: 'キュ'},
        {english: 'kyo', jap: 'キョ'},
        {english: 'ga', jap: 'ガ'},
        {english: 'gi', jap: 'ギ'},
        {english: 'gu', jap: 'グ'},
        {english: 'ge', jap: 'ゲ'},
        {english: 'go', jap: 'ゴ'},
        {english: 'gya', jap: 'ギャ'},
        {english: 'gyu', jap: 'ギュ'},
        {english: 'gyo', jap: 'ギョ'},
        {english: 'sa', jap: 'サ'},
        {english: 'shi', jap: 'シ'},
        {english: 'su', jap: 'ス'},
        {english: 'se', jap: 'セ'},
        {english: 'so', jap: 'ソ'},
        {english: 'sha', jap: 'シャ'},
        {english: 'shu', jap: 'シュ'},
        {english: 'sho', jap: 'ショ'},
        {english: 'za', jap: 'ザ'},
        {english: 'ji', jap: 'ジ'},
        {english: 'zu', jap: 'ズ'},
        {english: 'ze', jap: 'ゼ'},
        {english: 'zo', jap: 'ゾ'},
        {english: 'ja', jap: 'ジャ'},
        {english: 'ju', jap: 'ジュ'},
        {english: 'jo', jap: 'ジョ'},
        {english: 'ta', jap: 'タ'},
        {english: 'chi', jap: 'チ'},
        {english: 'tsu', jap: 'ツ'},
        {english: 'te', jap: 'テ'},
        {english: 'to', jap: 'ト'},
        {english: 'cha', jap: 'チャ'},
        {english: 'chu', jap: 'チュ'},
        {english: 'cho', jap: 'チョ'},
        {english: 'da', jap: 'ダ'},
        {english: 'ji', jap: 'ヂ'},
        {english: 'zu', jap: 'ヅ'},
        {english: 'de', jap: 'デ'},
        {english: 'do', jap: 'ド'},
        {english: 'ja', jap: 'ヂャ'},
        {english: 'ju', jap: 'ヂュ'},
        {english: 'jo', jap: 'ヂョ'},
        {english: 'na', jap: 'ナ'},
        {english: 'ni', jap: 'ニ'},
        {english: 'nu', jap: 'ヌ'},
        {english: 'ne', jap: 'ネ'},
        {english: 'no', jap: 'ノ'},
        {english: 'nya', jap: 'ニャ'},
        {english: 'nyu', jap: 'ニュ'},
        {english: 'nyo', jap: 'ニョ'},
        {english: 'ha', jap: 'ハ'},
        {english: 'hi', jap: 'ヒ'},
        {english: 'fu', jap: 'フ'},
        {english: 'he', jap: 'ヘ'},
        {english: 'ho', jap: 'ホ'},
        {english: 'hya', jap: 'ヒャ'},
        {english: 'hyu', jap: 'ヒュ'},
        {english: 'hyo', jap: 'ヒョ'},
        {english: 'ba', jap: 'バ'},
        {english: 'bi', jap: 'ビ'},
        {english: 'bu', jap: 'ブ'},
        {english: 'be', jap: 'ベ'},
        {english: 'bo', jap: 'ボ'},
        {english: 'bya', jap: 'ビャ'},
        {english: 'byu', jap: 'ビュ'},
        {english: 'byo', jap: 'ビョ'},
        {english: 'pa', jap: 'パ'},
        {english: 'pi', jap: 'ピ'},
        {english: 'pu', jap: 'プ'},
        {english: 'pe', jap: 'ペ'},
        {english: 'po', jap: 'ポ'},
        {english: 'pya', jap: 'ピャ'},
        {english: 'pyu', jap: 'ピュ'},
        {english: 'pyo', jap: 'ピョ'},
        {english: 'ma', jap: 'マ'},
        {english: 'mi', jap: 'ミ'},
        {english: 'mu', jap: 'ム'},
        {english: 'me', jap: 'メ'},
        {english: 'mo', jap: 'モ'},
        {english: 'mya', jap: 'ミャ'},
        {english: 'myu', jap: 'ミュ'},
        {english: 'myo', jap: 'ミョ'},
        {english: 'ya', jap: 'ヤ'},
        {english: 'yu', jap: 'ユ'},
        {english: 'ye', jap: 'エ'},
        {english: 'yo', jap: 'ヨ'},
        {english: 'ra', jap: 'ラ'},
        {english: 'ri', jap: 'リ'},
        {english: 'ru', jap: 'ル'},
        {english: 're', jap: 'レ'},
        {english: 'ro', jap: 'ロ'},
        {english: 'rya', jap: 'リャ'},
        {english: 'ryu', jap: 'リュ'},
        {english: 'ryo', jap: 'リョ'},
        {english: 'wa', jap: 'ワ'},
        {english: 'wo', jap: 'ヲ'},
        {english: 'we', jap: 'ヱ'},
        {english: 'wi', jap: 'ヰ'},
        {english: 'n', jap: 'ン'},
    ];

    data.forEach(item => {
        if (!store.has(item.jap)) {
            store.set(item.english, item.jap);
        } else {
            console.warn(`Duplicate entry found for ${item.jap}`);
        }
    });

    return Array.from(store).map(([english, jap]) => ({ english, jap }));
};

export default createKatakanaStore;